name: CI
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo apt update
          sudo apt install devscripts equivs -yq
          yes | sudo mk-build-deps -i
          DEB_BUILD_OPTIONS=noautodbgsym sudo dpkg-buildpackage -b

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "libre"
          prerelease: false
          title: "Auto build libre"
          files: |
            /home/runner/work/linux-libre/*.deb
            /home/runner/work/linux-libre/linux-libre/*.deb

